version: '3.1'
name: explorer-db
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: fabricexplorer
      POSTGRES_USER: hppoc
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  postgres:      