version: '3.1'
name: explorer-db
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fabricexplorer
      POSTGRES_USER: hppoc
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080