version: '3.1'
name: postgres
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # default=postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres # default=$POSTGRES_USER
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=davidkhala@gmail.com # required env, must be a valid email address
      - PGADMIN_DEFAULT_PASSWORD=password # required env
