version: '3.1'
name: postgres
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres # default=postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres # default=$POSTGRES_USER
      PGDATA: /var/lib/postgresql/data # data volumne path, default=/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5

    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 8080:8080

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=davidkhala@gmail.com # required env, must be a valid email address
      - PGADMIN_DEFAULT_PASSWORD=password # required env
volumes:
  postgres:
    