
services:
  gremlin-server:
    image: tinkerpop/gremlin-server
    restart: always
    platform: linux/x86_64
    ports:
      - "8182:8182"
    volumes:
      - tinkerpop_data_container:/data

volumes:
  tinkerpop_data_container: